---
title: "travelSurveyTools-psrctest"
author: "suzanne"
date: "2024-01-05"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(dplyr)
library(devtools)
library(srvyr)
library(stringr)
library(data.table)
library(psrcelmer)
```

```{r}
#set config
usethis::use_git_config(user.name = "Ennazus", user.email = "childresssuzanne@gmail.com")

# #Go to github page to generate token
usethis::create_github_token()

#paste your PAT into pop-up that follows...
credentials::set_github_pat()

#now remotes::install_github() will work

# install Jan 11 version of package for consistency
remotes::install_github('RSGInc/travelSurveyTools', ref = "b3f264c", force = TRUE)
```
Note: it's still called rsgSurveyTools
```{r}
library(travelSurveyTools)
```

```{r}

hhts_connect <- function(connection = NULL){
  if(!is.null(connection)) return(connection)
   if(config::is_active('default')){
     con <- DBI::dbConnect(odbc::odbc(),
                           driver = "ODBC Driver 17 for SQL Server",
                           server = "AWS-PROD-SQL\\Sockeye",
                           database = "hhts_cleaning",
                           trusted_connection = "yes",
                           port = 1433)
   }else
  {
    con <- DBI::dbConnect(RSQLite::SQLite(), 'hh_survey.db')
  }
}

```

```{r}
# Point to where the 2023 codebook lives:
codebook_path = 'J:/Projects/Surveys/HHTravel/Survey2023/Data/data_deliverable_81823/codebook_guide/PSRC_Combined_Codebook_2023_08162023.xlsx'

# Read Data  ===================================================================

#data as delivered
hh<-get_table(db_name = "HouseholdTravelSurvey2023", "combined_data", "v_household")
person<-get_table(db_name = "HouseholdTravelSurvey2023", "combined_data", "v_person")
day<-get_table(db_name = "HouseholdTravelSurvey2023", "combined_data", "v_day")
vehicle<-get_table(db_name = "HouseholdTravelSurvey2023", "combined_data", "v_vehicle")
trip<-get_table(db_name ="HouseholdTravelSurvey2023", "combined_data", "v_trip")
# Codebook --------------------------------------------------------------------

variables = readxl::read_xlsx(
 codebook_path,
 sheet = 'variable_list_2023'
)

values =  readxl::read_xlsx(
 codebook_path,
 sheet = 'value_labels_2023'
)

setDT(variables)
setDT(values)

```


```{r }
setnames(hh, 'hhid', 'hh_id')
setnames(person, 'hhid', 'hh_id')
setnames(day, 'hhid', 'hh_id')
setnames(trip, c('hhid', 'tripid'), c('hh_id', 'trip_id'))
setnames(vehicle, c('hhid', 'vehid'), c('hh_id', 'vehicle_id'))
```


```{r }
values[, val_order := seq_len(nrow(values))]

setnames(values, 'final_label', 'label')

setnames(variables, 'description_2023', 'description')

setnames(variables, c('hh_23', 'per_23', 'veh_23', 'day_23', 'trip_23', 'location_final'),
         c('hh', 'person', 'vehicle', 'day', 'trip', 'location'))

setnames(variables, 'data_type_2023', 'data_type')

variables[, shared_name := ifelse(
        grepl('--', description),
        sub('_[^_]*$', '', variable), variable)
    ]

variables[, is_checkbox := ifelse(grepl('--', description), 1, 0)]

variable_list = variables[!is.na(hh) | !is.na(person) | !is.na(day) | !is.na(trip) | !is.na(vehicle) | location != 0]

setnames(day, 'day_weight_2023', 'day_weight')

setDT(hh)
setDT(person)
setDT(day)
setDT(vehicle)
setDT(trip)

```


```{r }
hts_data = list('hh' = hh, 'person' = person, 'day' = day, 'trip' = trip, 'vehicle' = vehicle)
```


```{r}
hts_summary(hts_data = hts_data, summarize_var = 'age', summarize_by = 'employment', variables_dt = variable_list, values_dt = values)

hts_summary(hts_data = hts_data, summarize_var = 'num_trips', summarize_by = 'employment', variables_dt = variable_list, values_dt = values)

hts_summary(hts_data = hts_data, summarize_var = 'speed_mph', summarize_by = 'employment', variables_dt = variable_list, values_dt = values)

hts_summary(hts_data = hts_data, summarize_var = 'race', summarize_by = 'employment', variables_dt = variable_list, values_dt = values)

hts_summary(hts_data = hts_data, summarize_var = 'employment', summarize_by = 'race', variables_dt = variable_list, values_dt = values)
```
